from .doctorRegistView import DoctorRegistView
from .nurseRegistView import NurseRegistView
from .recordRegistView import RecordRegistView
from .patientrecordRegistView import Patient_RecordRegistView
from .consultationRegistView import ConsultationRegistView
from .developmentSerializer import DevelopmentRegistView
from .patientRegistView import PatientRegistView
from .procedureRegistView import ProcedureRegistView
from .hospitalListView import HospitalListView
from .tokenCRUDView import TokenCRUDView
from .procedureListView import ProcedureListView
from .epsListView import EpsListView
from .recordListView import RecordListView
from .patientRUDView import PatientRUDView
from .doctorRUDView import DoctorRUDView
from .nurseRUDView import NurseRUDView
