from .doctorRegistView import DoctorRegistView
from .nurseRegistView import NurseRegistView
from .recordRegistView import RecordRegistView
from .patientrecordRegistView import Patient_RecordRegistView
